CREATE TABLE APP_USER_GROUP
(
  ID NUMBER(19,0) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  REMARKS VARCHAR2(500),
  CONSTRAINT USER_GROUP_PK PRIMARY KEY (ID)
);

CREATE TABLE APP_USER
(
  ID NUMBER(19,0) NOT NULL,
  FIRST_NAME VARCHAR2(50),
  LAST_NAME VARCHAR2(100),
  EMAIL VARCHAR2(100) NOT NULL,
  USER_GROUP_ID NUMBER(19,0) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (ID),
  CONSTRAINT USER_USER_GROUP_FK FOREIGN KEY (USER_GROUP_ID) REFERENCES APP_USER_GROUP(ID)
);
